name: job devcontainer-build

on:
  pull_request:
    paths:
      - .devcontainer/devcontainer.json
      - .devcontainer/Dockerfile
      - .github/workflows/job-devcontainer-build.yaml
  push:
    branches:
      - main
    paths:
      - .devcontainer/devcontainer.json
      - .devcontainer/Dockerfile
      - .github/workflows/job-devcontainer-build.yaml
  workflow_dispatch:

env:
  # Hostname of your registry
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: chrismckelt
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: 'devcontainer-prebuild-template'
  COMPARE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@70fccc794acd729b2b22dd6a326895f286447728
        with:
          registry: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: chrismckelt/devcontainer-prebuild-template
          push: filter
          refFilterForPush: refs/heads/main
          eventFilterForPush: workflow_dispatch

      - name: Push Image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push chrismckelt/devcontainer-prebuild-template:latest